function lambda = eigenvalJacobGLMFNet_Fac(par,~,~)
    t0 = par.t0(:)';
    t1 = par.t1(:)';
    A = par.G1(:)';
    B = par.G0(:)';
    d = par.d(:)';
    J = par.J(:)';
    rhoS = par.xS(:)';
    GammaS = par.zS(:)';
    l1 = (-1/2).*(1+J.*GammaS.*rhoS).^(-2).*t0.^(-1).*t1.^(-1).*(t0+(-1).*d.*t0+2.*J.*GammaS.*rhoS.*t0+d.*rhoS.*t0+...
        (-2).*J.*GammaS.*d.*rhoS.*t0+J.^2.*GammaS.^2.*rhoS.^2.*t0+2.*J.*GammaS.*d.*rhoS.^2.*t0+...
        (-1).*J.^2.*GammaS.^2.*d.*rhoS.^2.*t0+J.^2.*GammaS.^2.*d.*rhoS.^3.*t0+d.*t1+rhoS.*t1+...
        (-1).*d.*rhoS.*t1+2.*J.*GammaS.*d.*rhoS.*t1+2.*J.*GammaS.*rhoS.^2.*t1+(-2).*J.*GammaS.*d.*rhoS.^2.*t1+...
        J.^2.*GammaS.^2.*d.*rhoS.^2.*t1+J.^2.*GammaS.^2.*rhoS.^3.*t1+(-1).*J.^2.*GammaS.^2.*d.*rhoS.^3.*t1+...
        (-1).*t0.*t1+(-1).*J.*GammaS.*t0.*t1+(((d.*((-1)+rhoS)+(-1).*rhoS).*(1+J.*GammaS.*rhoS).^2.*t1+...
        (-1).*t0.*((1+d.*((-1)+rhoS)).*(1+J.*GammaS.*rhoS).^2+(-1).*(1+J.*GammaS).*t1)).^2+...
        (-4).*J.*(1+J.*GammaS.*rhoS).^2.*t0.*t1.*((B.*rhoS.*((-1)+d+rhoS+(-1).*d.*rhoS)+...
        J.*GammaS.^2.*rhoS.^2.*(d+rhoS+(-1).*d.*rhoS)+GammaS.*((-1).*d.*((-1)+rhoS).^2+rhoS.^2)).*t1+...
        t0.*(A.*d.*((-1)+rhoS).*rhoS+J.*GammaS.^2.*(1+d.*((-1)+rhoS)).*rhoS.^2+GammaS.*((-1)+...
        d.*((-1)+rhoS).^2+2.*rhoS)+(-1).*GammaS.*((-1)+2.*rhoS+J.*GammaS.*rhoS.^2).*t1))).^(1/2));
    l2 = (-1/2).*(1+J.*GammaS.*rhoS).^(-2).*t0.^(-1).*t1.^(-1).*(t0+(-1).*d.*t0+2.*J.*GammaS.*rhoS.*t0+d.*rhoS.*t0+...
        (-2).*J.*GammaS.*d.*rhoS.*t0+J.^2.*GammaS.^2.*rhoS.^2.*t0+2.*J.*GammaS.*d.*rhoS.^2.*t0+...
        (-1).*J.^2.*GammaS.^2.*d.*rhoS.^2.*t0+J.^2.*GammaS.^2.*d.*rhoS.^3.*t0+d.*t1+rhoS.*t1+...
        (-1).*d.*rhoS.*t1+2.*J.*GammaS.*d.*rhoS.*t1+2.*J.*GammaS.*rhoS.^2.*t1+(-2).*J.*GammaS.*d.*rhoS.^2.*t1+...
        J.^2.*GammaS.^2.*d.*rhoS.^2.*t1+J.^2.*GammaS.^2.*rhoS.^3.*t1+(-1).*J.^2.*GammaS.^2.*d.*rhoS.^3.*t1+(-1).*t0.*t1+...
        (-1).*J.*GammaS.*t0.*t1+(-1).*(((d.*((-1)+rhoS)+(-1).*rhoS).*(1+J.*GammaS.*rhoS).^2.*t1+...
        (-1).*t0.*((1+d.*((-1)+rhoS)).*(1+J.*GammaS.*rhoS).^2+(-1).*(1+J.*GammaS).*t1)).^2+...
        (-4).*J.*(1+J.*GammaS.*rhoS).^2.*t0.*t1.*((B.*rhoS.*((-1)+d+rhoS+(-1).*d.*rhoS)+...
        J.*GammaS.^2.*rhoS.^2.*(d+rhoS+(-1).*d.*rhoS)+GammaS.*((-1).*d.*((-1)+rhoS).^2+rhoS.^2)).*t1+...
        t0.*(A.*d.*((-1)+rhoS).*rhoS+J.*GammaS.^2.*(1+d.*((-1)+rhoS)).*rhoS.^2+GammaS.*((-1)+d.*((-1)+rhoS).^2+...
        2.*rhoS)+(-1).*GammaS.*((-1)+2.*rhoS+J.*GammaS.*rhoS.^2).*t1))).^(1/2));
    lambda = [l1;...
              l2];
end